In [1]:
import numpy as np

In [2]:
x = np.arange(0,20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [8]:
y = np.eye(4)

In [9]:
print(y)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
arr = np.zeros((2,4))

In [7]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])