In [28]:
import pandas as pd
import numpy as np

In [29]:
data_df=pd.read_csv('/home/leah/Downloads/Fish.csv') 

In [30]:
data_df.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [31]:
x=data_df.drop(['Weight','Species'],axis=1).values
y=data_df['Weight'].values

In [32]:
from sklearn.linear_model import LinearRegression

In [33]:
model = LinearRegression()
model

LinearRegression()

In [34]:
model.fit(x, y)

LinearRegression()

In [35]:
print('intercept:', model.intercept_)

intercept: -499.58695535694187


In [36]:
print('slope:', model.coef_)

slope: [ 62.35521443  -6.52675249 -29.02621861  28.29735132  22.47330665]


In [37]:
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 326.81612777  369.57859339  370.82418025  439.05613854  444.16916821
  466.12531938  496.15134252  473.62398623  511.95189321  540.44545602
  536.53040775  551.80179482  540.3150434   556.0586456   584.39982147
  607.28049765  608.21493286  602.63015994  645.87687859  629.752138
  636.94759733  671.89658763  645.00106119  651.90331312  670.71263903
  666.68027257  688.73713396  698.76730011  720.43978287  796.13010587
  803.62924782  807.54330665  867.35964459  911.56438073  894.45974647
  -89.13240595   34.59573548   76.61669964   91.9448575   141.5233585
  148.11845226  135.97771966  132.18181968  160.54902275  197.22186967
  182.36104273  197.43654712  210.10228652  225.46574556  221.7914616
  249.24362069  286.00318882  331.92493631  344.59908139  505.82109937
  301.84880663  305.71765485  373.5551134   539.81247674  695.31306022
  798.77573778   13.38283184   23.99680891   96.17908694  152.41893132
  192.66943342  192.27759854  219.17494849  241.65405111  298

In [40]:
x_new = np.arange(35).reshape((-1, 5))
print(x_new)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]


In [41]:
y_new = model.predict(x_new)
print(y_new)

[-3.89380864e+02 -1.51635799e+00  3.86348149e+02  7.74212655e+02
  1.16207716e+03  1.54994167e+03  1.93780617e+03]


In [ ]:
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)