In [1]:
#Import the neccesary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Retrieve my csv file
pima_data = pd.read_csv('pimadataset.csv')

In [3]:
#Confirm retrieval of dataset using .describe which shows a summery of numerical attributes
pima_data.describe

<bound method NDFrame.describe of      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627  

In [5]:
#Preprocess the dataset
#3.1 insert column head
datacolumns = (['Pregnancies','Glucose','Bloodpressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction',
                'age','outcome'])
pima_data.columns = datacolumns

In [6]:
#Display the column heads
pima_data.columns

Index(['Pregnancies', 'Glucose', 'Bloodpressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'age', 'outcome'],
      dtype='object')

In [7]:
#Display the first three rows
pima_data.head(3)

Pregnancies  Glucose  Bloodpressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   

   DiabetesPedigreeFunction  age  outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1

In [8]:
#Get information about the dataframe
pima_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   Bloodpressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   age                       768 non-null    int64  
 8   outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [9]:
#Data size
pima_data.shape

(768, 9)

In [10]:
pima_data.describe()

Pregnancies     Glucose  Bloodpressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         age     outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [11]:
#Computing the mean and standard deviation of each feature
pima_data.mean(axis = 0)

Pregnancies                   3.845052
Glucose                     120.894531
Bloodpressure                69.105469
SkinThickness                20.536458
Insulin                      79.799479
BMI                          31.992578
DiabetesPedigreeFunction      0.471876
age                          33.240885
outcome                       0.348958
dtype: float64

In [19]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

#Selecting data columns
x= pima_data[['Pregnancies','Glucose','Bloodpressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','age']]
y=pima_data[['outcome']]

#Fit and scale the data
scaled_data = scaler.fit_transform(x)
print(x)

     Pregnancies  Glucose  Bloodpressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  age  
0                       0.627   50  
1                       0.351   31  


In [20]:
#Save the processed dataset as CSV
x.to_csv('pima2.csv')

In [21]:
#split data set into training data set and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [22]:
#training sets
x_train

Pregnancies  Glucose  Bloodpressure  SkinThickness  Insulin   BMI  \
580            0      151             90             46        0  42.1   
418            1       83             68              0        0  18.2   
764            2      122             70             27        0  36.8   
363            4      146             78              0        0  38.5   
757            0      123             72              0        0  36.3   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
192            7      159             66              0        0  30.4   
629            4       94             65             22        0  24.7   
559           11       85             74              0        0  30.1   
684            5      136             82              0        0   0.0   

     DiabetesPedigreeFunction  age  
580                     0.371   21  
418                     0.624   27  
764                     0.340   27  
363                     0.520   67  
757                     0.258   52  
..                        ...  ...  
763                     0.171   63  
192                     0.383   36  
629                     0.148   21  
559                     0.300   35  
684                     0.640   69  

[537 rows x 8 columns]

In [23]:
y_train

outcome
580        1
418        0
764        0
363        1
757        1
..       ...
763        0
192        1
629        0
559        0
684        0

[537 rows x 1 columns]

In [24]:
x_test

Pregnancies  Glucose  Bloodpressure  SkinThickness  Insulin   BMI  \
661            1      199             76             43        0  42.9   
122            2      107             74             30      100  33.6   
113            4       76             62              0        0  34.0   
14             5      166             72             19      175  25.8   
529            0      111             65              0        0  24.6   
..           ...      ...            ...            ...      ...   ...   
165            6      104             74             18      156  29.9   
188            8      109             76             39      114  27.9   
334            1       95             60             18       58  23.9   
758            1      106             76              0        0  37.5   
34            10      122             78             31        0  27.6   

     DiabetesPedigreeFunction  age  
661                     1.394   22  
122                     0.404   23  
113                     0.391   25  
14                      0.587   51  
529                     0.660   31  
..                        ...  ...  
165                     0.722   41  
188                     0.640   31  
334                     0.260   22  
758                     0.197   26  
34                      0.512   45  

[231 rows x 8 columns]

In [25]:
y_test

outcome
661        1
122        0
113        0
14         1
529        0
..       ...
165        1
188        1
334        0
758        0
34         0

[231 rows x 1 columns]

In [26]:
#CREATE A LOGISTICS MODEL
#Import library
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [27]:
#Choose model hyperparameters
model = LogisticRegression()
model.fit(x,y)

/home/leah/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/leah/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [28]:
model.coef_

array([[ 1.17252335e-01,  3.35997997e-02, -1.40873875e-02,
        -1.27049271e-03, -1.24031910e-03,  7.72023854e-02,
         1.41904159e+00,  1.00354022e-02]])

In [29]:
model.intercept_

array([-7.70291006])

In [37]:
y_pred=model.predict(x_test)
print(y_pred)

[1 0 0 1 0 0 1 1 1 0 1 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0
 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 0 0 1
 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0
 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0
 0 0 0 1 0 0 1 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1
 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 1 1 1 0 0 0 0 0]


In [35]:
model.predict([[1,199,76,43,0,42.9,1.394,22]])

/home/leah/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])

In [38]:
#evaluate the model
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.08538474780512995

In [39]:
#Visualising the confusion matrix
confusion_matrix(y,model.predict(x))

array([[447,  53],
       [114, 154]])

In [40]:
print(classification_report(y,model.predict(x)))

              precision    recall  f1-score   support

           0       0.80      0.89      0.84       500
           1       0.74      0.57      0.65       268

    accuracy                           0.78       768
   macro avg       0.77      0.73      0.75       768
weighted avg       0.78      0.78      0.77       768

