In [17]:
import pandas as pd
import numpy as np

In [18]:
data_df=pd.read_csv('/home/leah/Downloads/realEstate.csv') 

In [19]:
data_df.head()

No  X1 transaction date  X2 house age  \
0   1             2012.917          32.0   
1   2             2012.917          19.5   
2   3             2013.583          13.3   
3   4             2013.500          13.3   
4   5             2012.833           5.0   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391                        47.3  
3     24.98746     121.54391                        54.8  
4     24.97937     121.54245                        43.1

In [20]:
#calculate correlation for all pairwise combinations
data_df['X3 distance to the nearest MRT station'].corr(data_df['X4 number of convenience stores'])

-0.6025191447226252

In [7]:
x=data_df.drop(['Y house price of unit area',],axis=1).values
y=data_df['Y house price of unit area'].values

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
model = LinearRegression()
model

LinearRegression()

In [10]:
model.fit(x, y)

LinearRegression()

In [11]:
print('intercept:', model.intercept_)

intercept: -14038.079782924411


In [12]:
print('slope:', model.coef_)

slope: [-3.59350128e-03  5.07908732e+00 -2.70841959e-01 -4.52079011e-03
  1.12927749e+00  2.24672892e+02 -1.44235635e+01]


In [13]:
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

predicted response:
[47.89494828 48.56266359 49.48549608 49.06033833 46.89537276 31.91889851
 39.33884835 47.54002053  9.81655865 35.48386229 34.29401738 53.78979552
 41.54535896 27.67273277 46.25647334 38.73649247 51.43047277 37.9292868
 47.38089493 48.26799893 35.95766929 50.11138559 29.50341213 48.5161202
 35.50368053 32.63559946 46.82956086 42.76561856 43.36789538 46.32719978
 13.89809241 41.15359321 31.29576969 47.00535857 47.72827054 33.70165743
 31.12724096 31.45055473 45.00438468 46.47306013 15.01052845 17.07419178
 37.12270337 40.76168072 48.22815789 40.29546715 47.30437819 38.02779522
 13.16548441 10.05136704 42.34410669 24.32725969 35.39205449 42.15990131
 46.01959847 23.86067762 43.89609878 46.45669327 14.0061475  41.22718249
 34.55078751 50.88818913 30.24001441 48.18696556 33.68817154 44.03927002
 47.57742051 47.58869518 43.67261577 45.65208957 54.76629818 35.51034432
 45.50794239 15.6859821  53.26095864 32.92408517 38.38559021 28.86900812
 33.30751556 28.52317152 45.21256

In [14]:
x_new = np.arange(35).reshape((-1, 7))
print(x_new)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [15]:
y_new = model.predict(x_new)
print(y_new)

[-12992.21575158 -11478.96459036  -9965.71342913  -8452.4622679
  -6939.21110668]


In [16]:
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)

coefficient of determination: 0.5833632616324598
